# Generated by Django 5.1.4 on 2024-12-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='Not specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
